# name: CI OUTPUTS

# on:
#   push:
#     branches: [main]

# permissions:
#   contents: write

# jobs:
#   log-numbers:
#     runs-on: ubuntu-latest
#     outputs:
#       number_1: ${{ steps.num_1.outputs.number }}
#       number_2: ${{ steps.num_2.outputs.number }}
#     steps:
#       - id: num_1
#         run: echo "number=12" >> "$GITHUB_OUTPUT"
#       - id: num_2
#         run: echo "number=34" >> "$GITHUB_OUTPUT"

#   calc-output:
#     runs-on: ubuntu-latest
#     needs: log-numbers
#     env:
#       NUMBER_1: ${{ needs.log-numbers.outputs.number_1 }}
#       NUMBER_2: ${{ needs.log-numbers.outputs.number_2 }}
#     steps:
#       - uses: actions/checkout@v3

#       - name: Make script executable 
#         run: |
#           chmod u+x scripts/data_integrate.sh
#           outputs=$(./scripts/data_integrate.sh)
#           wc -l db/database.csv

#       - name: Create report file
#         run: |
#           date +"%Y-%m-%d %H:%M:%S" > report.txt
#           cat calculation_output.txt >> report.txt

#       - name: Stage and Commit Report
#         run: |
#           git config --global user.name "Seniormanx"
#           git config --global user.email "waletomi5@gmail.com"
#           git add db/database.csv
#           git commit -m "Automated "

#       - name: Push Changes
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         run: git push