name: Data Checker

on:
  push:
    paths:
      - 'data/**'
  pull_request:
    paths:
      - 'data/**'

jobs:
  detect_new_data:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Detect changed files in the 'data-hub' folder
      - name: Display changed files
        id: detect-data
        uses: tj-actions/changed-files@v45
        with:
          files: data-hub/*.{csv}

      # Step 3: Run data integration script if changes are detected
      - name: Run data integration script if changes detected
        if: steps.detect-data.outputs.any_changed == 'true'
        run: |
          echo "Changes detected in 'data-hub' folder."
          echo "List of changed files: ${{ steps.detect-data.outputs.all_changed_files }}"

  data_integration:
    runs-on: ubuntu-latest
    needs: detect_new_data
    if: steps.detect-data.outputs.any_changed == 'true'

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Make the Bash script executable
      - name: Make the script executable
        run: chmod +x scripts/data_integrate.sh

      # Step 3: Run the Bash script
      - name: Run the Bash script
        run: ./scripts/data_integrate.sh
