name: Data Checker

on:
  push:
    paths:
      - 'data-hub/**'
      - 'scripts/**'
  pull_request:
    paths:
      - 'data-hub/**'
      - 'scripts/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install ShellCheck
        run: sudo apt install shellcheck

      - name: Run Linter
        run:  shellcheck scripts/*.sh

  data_integration:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Make the Bash script executable
      - name: Make the script executable
        run: chmod +x scripts/data_integrate.sh

      # Step 3: Run the Bash script
      - name: Run the Bash script
        run: ./scripts/data_integrate.sh
